### ISSUE TITLE
32-bit build possible?

### ISSUE THREAD

**Issue by Yetangitu** [DD1984/SpaceMouse_Fusion360_Wine#1]
I'm trying to get this to work on a 32-bit installation for Sketchup 2016. To get this to work I'd need a 32-bit bit build of `siappdll.dll` but I don't have any Windows build infrastructure set up. Could you put a 32-bit version of the DLL in the repo as well so I can have a go at testing with Sketchup?

**Comment by Yetangitu** [comment]
Never mind, I made one myself (had to port that bit of assembly) only to find out the Sketchup extension does not seem to use the DLL, nor do the demo programs. In fact I have not found any program interested in loading `siappdll.dll`. Which version of the driver is this thing based on?

**Comment by DD1984** [comment]
hello, sorry for late answer.
0. i check this dll with fusion360 ("legacy driver" selected in fusion360 preference) and with demo programs from 3dconnexion driver package (latest drivers for spacemouse compact, but all demo apps are very old)
1. if you use 32bit windows app under wine on 64bit host - it possible to recompile this lib to 32bit, and it must work, but i did not check this, if you need to use 32bit app on 32bit host you must rewrite functions that use linux kernel syscall - linux syscall conventions are differ for 64bit and 32bit  for x86 cpu
2.  there are three types of 3d mouse usage in windows:
 - new driver api (fusion360)
 - old driver api (siappdll.dll - fusion360 with "legacy driver" selected)
 - direct using usb hid api (kicad)
 i do not know what type is used in Sketchup 2016, but you can check is this lib usage by app using wine debug variable - to check is this lib are loading by wine on app start. And be sure that you do not have original lib installed in system32 dir or in other windows dll path
