### ISSUE TITLE
Failed to create socket with err: 0xc0000002

### ISSUE THREAD

**Issue by ryryog25** [DD1984/SpaceMouse_Fusion360_Wine#3]
My issue seems similar to https://github.com/DD1984/SpaceMouse_Fusion360_Wine/issues/2#issuecomment-1449801112

I had `siappdll.dll` working previously, so I'm not sure what's going on here, but I get:

```
[*** SPMOUSE ***] INFO Starting siappdll replacement
[*** SPMOUSE ***] INFO Siappdll loaded:
[*** SPMOUSE ***] INFO Loaded from: C:\Program Files\Autodesk\webdeploy\producti
on\dabca83aceed67f5b8555a5b9697a3fc08792c77\siappdll.dll
[*** SPMOUSE ***] INFO Creating socket
[*** SPMOUSE ***] ERROR Failed to create socket with err: 0xc0000002
[*** SPMOUSE ***] ERROR connection to daemon failed
```

When trying to use it now, and of course the Spacemouse doesn't work.

I've tried to do some digging to figure out what the error even is, and digging through the source code, where syscall 41 is made, tracing that all the way back through ERR_PTR... it seems like the int is just a pointer? I'm not sure, but none of the int values associated with the errno (or similar) enums go that high in value.

I can't find anything referencing an error like this, and I don't have the toolchain to recompile the dll to try and make it dereference the pointer before outputting.

Of course I have suspicion it's a permissions error of some kind, but I'm not sure what to do to try and debug this further.

**Comment by DD1984** [comment]
Hello, i have tried to investigate (into kernel code) what 0xc0000002 value mean and have no results.
This is not one of errno, but it is bigger than max possible fd in system.
I think that this value may right value, but we must mask it with max fd in system, for example.
we may check how this syscall execute libc for example.

second idea - check is this error occure  with simple test program from win_dll_test folder - i think it will more simple to debug
Pls, try it, if you have possibility

**Comment by DD1984** [comment]
pls try to use latest dll - added second attempt to create socket using 32b int80h syscall

**Comment by ryryog25** [comment]
Just tried the new dll. Tested first with the test program under WINE and working, then under Fusion360. The updated DLL succeeds in creating the socket, returning a valid file descriptor, however it has issues accessing the socket file now:
```
[*** SPMOUSE ***] INFO Starting siappdll replacement
[*** SPMOUSE ***] INFO Siappdll loaded:
[*** SPMOUSE ***] INFO Loaded from: C:\Program Files\Autodesk\webdeploy\producti
on\dabca83aceed67f5b8555a5b9697a3fc08792c77\siappdll.dll
[*** SPMOUSE ***] INFO Creating socket
[*** SPMOUSE ***] ERROR l_socket() return err: 0xc0000002
[*** SPMOUSE ***] INFO trying l_socket_int80h()
[*** SPMOUSE ***] INFO fd: 426
[*** SPMOUSE ***] INFO Attempting to connect to /var/run/spnav.sock
[*** SPMOUSE ***] ERROR Failed to connect
[*** SPMOUSE ***] ERROR connection to daemon failed
```

**Comment by ryryog25** [comment]
Just double-checked since I had a suspicion: The jet.exe test works in the last commit (without the new method for socket creation) as well, running under the same Wine prefix, so this seems to be Fusion specific. The fact that the socket was created successfully is promising though. My first thought is maybe a permissions error accessing the spnav.sock?

**Comment by DD1984** [comment]
[siappdll.tar.gz](https://github.com/DD1984/SpaceMouse_Fusion360_Wine/files/12566821/siappdll.tar.gz)
pls test attached dll - debug was added - print connect() error, print rax reg after syscall

**Comment by ryryog25** [comment]
Just tested it out, here's the output:
```
[*** SPMOUSE ***] INFO Starting siappdll replacement
[*** SPMOUSE ***] INFO Siappdll loaded:
[*** SPMOUSE ***] INFO Loaded from: C:\Program Files\Autodesk\webdeploy\producti
on\dabca83aceed67f5b8555a5b9697a3fc08792c77\siappdll.dll
[*** SPMOUSE ***] INFO Creating socket
[*** SPMOUSE ***] ERROR l_socket() return err: 0xc0000002
[*** SPMOUSE ***] INFO trying l_socket_int80h()
[*** SPMOUSE ***] INFO fd: 273
[*** SPMOUSE ***] INFO Attempting to connect to /var/run/spnav.sock
[*** SPMOUSE ***] ERROR l_connect() return err: 0xc0000005
[*** SPMOUSE ***] ERROR Failed to connect
[*** SPMOUSE ***] ERROR connection to daemon failed
```

Same deal though, the error codes don't go that high... unsure how it may need to be manipulated...

**Comment by DD1984** [comment]
do you see **rax=0000000000000000** debug?
something like this:
```
[*** SPMOUSE ***] INFO Starting siappdll replacement  
[*** SPMOUSE ***] INFO Siappdll loaded: 
[*** SPMOUSE ***] INFO Loaded from: C:\users\dmitriy\Local Settings\Application Data\Autodesk\webdeploy\production \dabca83aceed67f5b8555a5b9697a3fc08792c77\siappdll.dll 
[*** SPMOUSE ***] INFO Creating socket 
rax=0000000000000154 
[*** SPMOUSE ***] INFO fd: 340 
[*** SPMOUSE ***] INFO Attempting to connect to /var/run/spnav.sock 
rax=0000000000000000
```
error code 0xc... looks like windows exception, but i do not understand how it was generated

**Comment by ryryog25** [comment]
I found this: https://nolongerset.com/breaking-down-windows-error-codes/

And that seems to indicate it's a Win32 err after removing the irrelevant parts of the error code: 

`0x00000003   ERROR_PATH_NOT_FOUND | The system cannot find the path specified.`

**Comment by ryryog25** [comment]
Also, no I did not see that `rax=...` in the debug output, only the new `l_connect` debug.

**Comment by DD1984** [comment]
pls, try dll from latest commit - added api switch when error occur - from syscall to int80h for all functions

i do not understand why but looks like all 64b syscall failed in your case (only with fusion360), the reason of this need more investigation - this may be stack alignment or similar global reason

**Comment by ryryog25** [comment]
Awesome! Switching to 80h calls fixed it it seems. I don't get any errors during startup and SpaceMouse works in Fusion now!

Now that I think about it, WINE is running in 32-Bit mode, so that's probably why the 64b syscalls don't work.

Thank you so much for your time looking into this!

```
[*** SPMOUSE ***] INFO Starting siappdll replacement
[*** SPMOUSE ***] INFO Siappdll loaded:
[*** SPMOUSE ***] INFO Loaded from: C:\Program Files\Autodesk\webdeploy\producti
on\dabca83aceed67f5b8555a5b9697a3fc08792c77\siappdll.dll
[*** SPMOUSE ***] INFO Creating socket
[*** SPMOUSE ***] ERROR l_socket() return err: 0xc0000002
[*** SPMOUSE ***] INFO trying l_socket_int80h()
[*** SPMOUSE ***] INFO Using int80h api!!!
[*** SPMOUSE ***] INFO fd: 302
[*** SPMOUSE ***] INFO Attempting to connect to /var/run/spnav.sock
```

**Comment by DD1984** [comment]
No, wine running in 64b mode, maybe wine catch this 64b syscall as windows syscall - there are this possibility - maybe we will  know this in future.
Thank you for help too!

**Comment by ryryog25** [comment]
:+1:
